# Configuration Netlify pour le portfolio Alberto Kitenge

[build]
  # Commande de build
  command = "npm run build"
  # Dossier de publication
  publish = "dist"

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "18"
  NODE_ENV = "production"

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance
    Cache-Control = "public, max-age=31536000, immutable"

# Headers spécifiques pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour le HTML (pas de cache)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
